# Generated by Django 3.1.1 on 2020-12-22 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="card", old_name="stuff", new_name="suite",),
        migrations.RemoveField(model_name="deck", name="things",),
        migrations.AddField(
            model_name="card", name="dealt", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="card",
            name="deck",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="game.deck"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deck",
            name="game",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
            preserve_default=False,
        ),
    ]
