# Generated by Django 3.1.1 on 2020-12-23 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0002_auto_20201222_1750"),
    ]

    operations = [
        migrations.RemoveField(model_name="card", name="suite",),
        migrations.RemoveField(model_name="deck", name="game",),
        migrations.AddField(
            model_name="card",
            name="suit",
            field=models.CharField(
                choices=[("H", "Hearts"), ("S", "Spades"), ("C", "Clubs"), ("D", "Diamonds")],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="deck", name="title", field=models.CharField(default="Deck", max_length=50),
        ),
        migrations.AddField(
            model_name="deck",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decks",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="active_deck",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="game.deck"
            ),
        ),
        migrations.AddField(
            model_name="game", name="game_can_lose", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="outcome",
            field=models.CharField(
                choices=[("W", "Won"), ("L", "Lost"), ("U", "Undecided")], default="U", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card", name="value", field=models.CharField(default="Ace", max_length=5),
        ),
        migrations.AlterField(
            model_name="game",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="deck",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_user_title_pair"
            ),
        ),
    ]
