# Generated by Django 3.1.1 on 2020-12-23 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_auto_20201223_1922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cards", to="game.deck"
            ),
        ),
    ]
